# Site settings
title: WTM Zaragoza 2017
email: womentechmakerszgz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email: womentechmakerszgz@gmail.com
facebook_username:
twitter_username: WTMZaragoza
github_username: MulleresTechZgz
address:
  - line: ETOPIA Centro de Arte y Tecnología
  - line: Av. de la Ciudad de Soria, 8 (50003) Zaragoza
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
theme: 


#Introduction
intro_event:

#List for event info
event_infos:
  - title: ¿Qué es Women Techmakers?
    content: Se trata de una iniciativa promovida a nivel global por Google para <strong>visibilizar a las mujeres</strong> en el ámbito de la tecnología.<br/><br/>Women Techmakers quiere crear una comunidad con visibilidad, generando recursos que impulsen la innovación y la participación de las mujeres en este campo.<br/><br/>Estos eventos están diseñados para promover la inclusión de las mujeres en la tecnología.
    image: organizersmad.jpg
  - title: ¿A quién está dirigido el evento?
    content: Se trata de un <strong>evento abierto</strong> a cualquier persona interesada en el mundo de la tecnología.<br/><br/>Queremos abarcar diferentes temas como <strong>nuevas tecnologías, agile, comunicación, desarrollo web, UX</strong> o cualquier tema interesante del sector.<br/><br/>La asistencia al evento está abierta tanto a hombres como a mujeres, pero las ponentes serán únicamente mujeres, ya que uno de los objetivos es darles visibilidad así como ofrecer ayuda y colaboración.
    image: audience.jpg
  - title: ¿Dónde se ha celebrado hasta ahora?
    content: <ul class="wtm-inline-list"> <li><i class="fa fa-map-marker"></i> Barcelona</li> <li><i class="fa fa-map-marker"></i> Logroño</li> <li><i class="fa fa-map-marker"></i> Madrid</li> <li><i class="fa fa-map-marker"></i> Málaga</li> <li><i class="fa fa-map-marker"></i> Menorca</li> <li><i class="fa fa-map-marker"></i> Reus</li> <li><i class="fa fa-map-marker"></i> Salamanca</li> <li><i class="fa fa-map-marker"></i> Tenerife</li> <li><i class="fa fa-map-marker"></i> Valencia</li></ul>
    image: girs_at_wtm_mad.jpg
  - title: Algunas cifras
    content: <span class="wtm-highlight">9</span> ponentes en Barcelona<br/> <span class="wtm-highlight">10</span> ponentes en Menorca<br/> <span class="wtm-highlight">6</span> ponentes en Tarragona<br/> <span class="wtm-highlight">3</span> ponentes en Salamanca<br/> <span class="wtm-highlight">13</span> ponentes en Valencia<br/> <span class="wtm-highlight">33</span> ponentes en Madrid
    image: chatting.jpg
  - title: WTM Madrid 2017
    content: Consiguió <strong>más de 33 ponentes</strong>.<br/><br/>El 60% de las ponentes dieron una charla por primera vez.<br/><br/>Ampliaron el círculo de networking de muchas mujeres.<br/><br/>Ayudaron a las empresas a <strong>encontrar mujeres profesionales</strong> en el sector de la tecnología.<br/><br/>También nos dieron el empujón para que este año organicemos Women Techmakers Zaragoza.
    image: speakers.jpg

#List for organizers
organizers:
  - name: Esther Borao
    text: 
    image:
    twitter_account: EstherBorao
  - name: Miriam Durán
    text: 
    image:
    twitter_account: miripi
  - name: Cynthia Gálvez
    text: 
    image:
    twitter_account: icynthia
  - name: Patricia Heredia
    text: 
    image:
    twitter_account: pherediagil
  - name: Laura Lacarra
    text: 
    image:
    twitter_account: LauraLacarra
  - name: Cristina Pérez
    text: 
    image:
    twitter_account: cristinapg
  - name: Jessica Redrado
    text: 
    image:
    twitter_account: Jessi_Redrado
  - name: Paloma Royo
    text: 
    image:
    twitter_account: Paloma09284141
  - name: Ana Sánchez
    text: 
    image:
    twitter_account: _Ana_Sanchez_
  - name: Nieves Sancho
    text: 
    image:
    twitter_account: Nievesancho


#List for speakers
speakers:
  - name: Aparece aquí!
    text: Aparece aquí!!
    image: fa-cloud

#List for sponsors
sponsors_platinum:
  - name: Aparece aquí!!
    text: Aparece aquí!!
    image: fa-cloud

sponsors_gold:
  - name: Aparece aquí!!
    text: Aparece aquí!!
    image: fa-cloud

sponsors_silver:
  - name: Aparece aquí!!
    text: Aparece aquí!!
    image: fa-cloud


sponsors_others:
  - name: Aparece aquí!!
    text: Aparece aquí!!
    image: fa-cloud
